AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - spec/*
    - ms_teams.gemspec

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false
  
Layout/SpaceInsideParens: 
  Enabled: false
  
Style/HashSyntax:
  Enabled: false
  
Style/SymbolArray:
  Enabled: false
  
Layout/TrailingEmptyLines:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false
